version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
